package main

import (
	"cmp"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"path/filepath"
	"slices"
	"strings"
)

func snapshot(ctx context.Context, dataDir, skillsDir, project, title string) (string, error) {
	name, err := normalizeName(project)
	if err != nil {
		return "", fmt.Errorf("project: %w", err)
	}
	if err := validateText("skill name", title); err != nil {
		return "", err
	}
	if strings.ContainsAny(title, "\r\n") {
		return "", fmt.Errorf("skill name must fit on one line")
	}
	memories, err := loadMemories(ctx, dataDir, name)
	if err != nil {
		return "", err
	}
	data := renderSkill(name, strings.TrimSpace(title), memories)
	if err := ctx.Err(); err != nil {
		return "", err
	}
	dir, err := openProjectDir(skillsDir, name, true)
	if err != nil {
		return "", err
	}
	defer dir.Close()
	if err := writeFile(dir, "SKILL.md", data, true); err != nil {
		return "", fmt.Errorf("write skill: %w", err)
	}
	return filepath.Join(skillsDir, name, "SKILL.md"), nil
}

func loadMemories(ctx context.Context, dataDir, name string) ([]memory, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	dir, err := openProjectDir(dataDir, name, false)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, fmt.Errorf("no memories saved for project %q", name)
	}
	if err != nil {
		return nil, err
	}
	defer dir.Close()
	entries, err := fs.ReadDir(dir.FS(), ".")
	if err != nil {
		return nil, fmt.Errorf("list memories: %w", err)
	}
	var memories []memory
	for _, entry := range entries {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}
		if !entry.Type().IsRegular() {
			return nil, fmt.Errorf("memory %q must be a regular file", entry.Name())
		}
		data, err := dir.ReadFile(entry.Name())
		if err != nil {
			return nil, fmt.Errorf("read memory %q: %w", entry.Name(), err)
		}
		var m memory
		if err := json.Unmarshal(data, &m); err != nil {
			return nil, fmt.Errorf("decode memory %q: %w", entry.Name(), err)
		}
		if err := m.validate(name, entry.Name()); err != nil {
			return nil, fmt.Errorf("validate memory %q: %w", entry.Name(), err)
		}
		memories = append(memories, m)
	}
	if len(memories) == 0 {
		return nil, fmt.Errorf("no memories saved for project %q", name)
	}
	slices.SortFunc(memories, func(a, b memory) int {
		return cmp.Or(cmp.Compare(a.Created, b.Created), cmp.Compare(a.ID, b.ID))
	})
	return memories, nil
}

func renderSkill(name, title string, memories []memory) []byte {
	var b strings.Builder
	// JSON strings are also valid YAML quoted scalars, including numeric names.
	quotedName, _ := json.Marshal(name)
	description, _ := json.Marshal("Apply learned preferences and instructions for " + name + ". Use when working on the " + name + " project.")
	fmt.Fprintf(&b, "---\nname: %s\ndescription: %s\n---\n\n# %s\n\n", quotedName, description, title)
	fmt.Fprintf(&b, "Project: %s\n\n", name)
	b.WriteString("These memories were collected from project conversations. Apply relevant instructions when working on this project. Later memories may refine earlier ones.\n\n")
	b.WriteString("<!-- Generated by recall snapshot. Save new memories with recall save, then regenerate. -->\n\n## Memories\n\n")
	seen := make(map[string]bool)
	for _, m := range memories {
		if seen[m.Text] {
			continue
		}
		seen[m.Text] = true
		// Keep multiline Markdown intact, including fenced code and indentation.
		b.WriteString(m.Text)
		b.WriteString("\n\n")
	}
	return []byte(b.String())
}
